[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "snippet-uiautomator"
version = "1.1.2"
description = "A Python wrapper for Android UI Automator"
authors = [{ name = "Google Inc." }]
maintainers = [{ name = "Kolin Lu", email = "kolinlu@google.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7"
keywords = ["uiautomator", "mobly", "android"]
dependencies = [
    "mobly>=1.12.2",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "pyink",
    "pytest",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/google/snippet-uiautomator"
Repository = "https://github.com/google/snippet-uiautomator.git"
Issues = "https://github.com/google/snippet-uiautomator/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["snippet_uiautomator*"]

[tool.setuptools.package-data]
snippet_uiautomator = ["android/app/uiautomator.apk"]

[tool.pytest.ini_options]
addopts = "--cov=snippet_uiautomator --cov-report html"
pythonpath = "."

[tool.pyink]
pyink-indentation = 2
pyink-use-majority-quotes = true
line-length = 80
preview = true
